# Generated by Django 4.1.7 on 2023-02-16 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_song_audio_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='artist',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='song',
            name='title',
            field=models.TextField(max_length=50),
        ),
    ]
