# Generated by Django 4.1.3 on 2023-03-14 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_artist_remove_song_audio_link_remove_song_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='bio',
        ),
    ]
