# Generated by Django 4.1.3 on 2023-04-10 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0006_remove_artist_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='lastname',
        ),
    ]
