# Generated by Django 4.1.3 on 2023-05-03 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0007_remove_registration_firstname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='last_played',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
