# Generated by Django 4.1.3 on 2023-05-05 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0009_favourite_remove_artist_photo_remove_song_album_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='favourite',
            name='artist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='music.artist'),
        ),
        migrations.AddField(
            model_name='favourite',
            name='last_played',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='favourite',
            name='audio_file',
            field=models.FileField(upload_to='songs/'),
        ),
        migrations.AlterField(
            model_name='song',
            name='artist',
            field=models.ForeignKey(null='True', on_delete=django.db.models.deletion.CASCADE, to='music.artist'),
        ),
    ]
