# Generated by Django 4.1.3 on 2023-05-09 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0014_remove_song_duration_song_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='last_played',
        ),
    ]
