# Generated by Django 4.1.3 on 2023-05-24 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0016_playlist_favourite'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Playlist',
        ),
    ]
