# Generated by Django 4.1.3 on 2023-05-24 14:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0017_delete_playlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='password',
            field=models.CharField(max_length=50, null=True, validators=[django.core.validators.MinLengthValidator(8)]),
        ),
    ]
