# Generated by Django 4.1.3 on 2023-05-25 12:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('music', '0019_alter_registration_password'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Favourite',
            new_name='Favorite',
        ),
        migrations.AddField(
            model_name='song',
            name='fav',
            field=models.ManyToManyField(blank=True, related_name='favorite_songs', to='music.registration'),
        ),
    ]
